### ISSUE TITLE
Know limitations github issue reference is missing

### ISSUE THREAD

**Issue by thomasmodeneis** [rethinkdb/logstash-input-rethinkdb#8] opened 2016-01-27 12:34 UTC
Hi,
Could you please provide us the link for the github issue where the known limitation 1 is being tracked on the readme file? that will help people to identify how long this limitation will be in place in order to decide to use this software or not.

Thanks

**Comment by deontologician** [comment] 2016-01-28 22:44
Currently, this is scheduled for 2.3, the next release. I added the link to the README. Once 2.3 is released, I'll need to make a minor modification to the logstash plugin to get it to resume changefeeds

**Comment by deontologician** [comment] 2016-01-28 22:45
For reference, the issue is rethinkdb/rethinkdb#3741

**Comment by danielmewes** [comment] 2016-01-28 22:55
@deontologician I think you linked the wrong issue. The correct one:
https://github.com/rethinkdb/rethinkdb/issues/3471

(and to be honest I think it will probably be pushed into 2.4, because 2.3 is already pretty full :-( )

**Comment by deontologician** [comment] 2016-01-28 23:02
issue number dyslexia strikes again!

**Comment by deontologician** [comment] 2016-01-28 23:03
The link in the README is correct though, I copy/pasted that. So re-closing this

**Closed as completed by deontologician** 2016-01-28 23:03 UTC

**Comment by thomasmodeneis** [comment] 2016-02-01 16:29
Thanks guys, great info.
I will keep an eye on the ticket.
Cheers
